version: "3.3"
services:
  api:
    build: api
    ports:
      - "5000:5000"
  web:
    build: web-ui
    ports:
      - "3000:3000"
  collector:
    build: collector
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - "env.influxdb"
    volumes:  
      - /srv/docker/influxdb/data:/var/lib/influxdb
