version: "3.3"
services:
  api:
    build: api
    ports:
      - "5000:5000"
  web:
    build: web-ui
    ports:
      - "3000:3000"
  collector:
    build: collector
    environment:
      - API_URL=${API_URL}
      - WS_URL=${WS_URL}
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - "env.influxdb"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
